---
title: "ETFsIFBacktestingStrategy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TTR lets use a little of thecnical analisys finding the  overbought and oversold etf or investmend funds 


*italic*   **bold**

```{r  aa, echo=T , message=F, warning=F}

rm(list = ls())

df <-readRDS("../input/historical.prices.dETFEI.date.rds")

df[,1] <- as.Date(df[,1], format="%a, %b %d, %Y") # date format
converToNumeric = function(x) { as.numeric(gsub(",", "", x, fixed = TRUE)) }
df[,2:5] = sapply(df[,2:5], converToNumeric) # numeric format


library(TTR) #  rsi() for calculating simple moving average

vector <- unique(df$isin)
dfa <- data.frame(stringsAsFactors=FALSE) 

for (i in vector)
{

  
  e <- dplyr::filter(df,  isin == i)

if(nrow(e) > 14)  
  {
      e <- e[order(as.Date(e$date, format="%Y-%m-%d")),]
      
      rsi <- RSI(e$Close, n=14)
      e$rsi <-rsi
      tail <- tail(e, 1)
      dfa <-rbind( dfa ,tail )
  }
}


t <-tail (dfa[order(dfa$rsi),], 1)

h <-head (dfa[order(dfa$rsi),], 1)

```


# lets see the overboguht / # lets see the oversold 




```{r  eda1, echo=T , message=F, warning=F}
library(plotly)


p1 <- plot_ly() %>% 
  add_trace(data=dplyr::filter(df,  isin == h$isin),
            x = ~date, y = ~Close, type="scatter", mode="lines", name = h$isin) 
p1


p1 <- plot_ly() %>% 
  add_trace(data=dplyr::filter(df,  isin == t$isin),
            x = ~date, y = ~Close, type="scatter", mode="lines", name = t$isin) 
p1

``` 




```{r scraping,include=FALSE} 


sma50200<-function(dataset){ 

ob <- dataset[order(as.Date(dataset$date, format="%Y-%m-%d")),]

ob$SMA50 <- SMA(ob$Close, 50)
ob$SMA200 <- SMA(ob$Close, 200)


p <-plot_ly() %>% 
  add_trace(data= ob,
            x = ~date, y = ~Close, type="scatter", mode="lines", name = "historical.data.overbought") %>% 
  add_trace(x = ~date,y = ~SMA50, type="scatter", mode="lines", name = "SMA50") %>% 
   add_trace(x = ~date,y = ~SMA200, type="scatter", mode="lines", name = "SMA200") 

return(p)  

}


historical.data.overbought <- df %>%  filter(isin == t$isin)
historical.data.oversell <- df %>%  filter(isin == h$isin)

pb<-sma50200(historical.data.overbought)
ps<-sma50200(historical.data.oversell)
pb
ps 
 
```


# lets calculate how many are oversell but they are in positive trend so there is a chance to make some money


```{r pressure, echo=FALSE}


vector <- unique(df$isin)

R52 <- data.frame(stringsAsFactors=FALSE) 


for (i in vector)
{

    e <- dplyr::filter(df,  isin == i)

if(nrow(e) > 200)  
  {
      e <- e[order(as.Date(e$date, format="%Y-%m-%d")),]
      
      e$SMA50 <- SMA(e$Close, 50)
      e$SMA200 <- SMA(e$Close, 200)
      e$rsi <- RSI(e$Close, n=14)
      tail <- tail(e, 1)
      R52 <-rbind( R52 ,tail )
}
  else {print(i)}
}

thechosenones <-R52 %>% filter (rsi < 40) %>% filter (SMA200 < SMA50)


historical.data.thechosenones <- df %>%  filter(isin == thechosenones$isin)
ps<-sma50200(historical.data.thechosenones)
ps

```

# what kind of etfs we have ?
# how many we have by 

```{r pressure, echo=FALSE}

aa <- dfa %>% group_by( category) %>%  filter(type == 'ETFEI' )  %>% summarise(count= n())

pp <- plot_ly(aa, x = ~category, y = ~count,  
              type = 'scatter' , mode = 'markers', marker = list(size = 15))  %>% 

layout(title = "numbers of etfs by category",  showlegend = TRUE)
pp


aa <- dfa %>% group_by( category) %>% filter(type == 'ITEI' )  %>%   summarise(count= n())

pp <- plot_ly(aa, x = ~category, y = ~count,  
              type = 'scatter' , mode = 'markers', marker = list(size = 15))  %>% 

layout(title = "numbers of IF by category",  showlegend = TRUE)
pp

```


# lets inferir some basica materials

```{r pressure, echo=FALSE}
thingslooklikeMaterial <- c("gold",'Physical', 'silver')


MFEIInc <- dfa  %>%  filter( grepl(paste(thingslooklikeMaterial, collapse="|"),LegalName , ignore.case=T )) 

```





