---
title: "signalSelected"
author: "david soto"
date: "9/28/2017"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
# Clear the workspace
require(quantmod)
require(PerformanceAnalytics)

setwd("~/dataScience/blog/mfunds/")
selected <- readRDS("input/selected50.rds") %>% as.data.frame()



library(jsonlite) 
library(XML)

library(RCurl)
library(stringr)
library(plyr)


# Load the required libraries
funds <- readRDS("input/ftfunds.rds")


LU0448836352 <- filter(funds, isin == 'LU0448836352')

x <- xts(LU0448836352$close,LU0448836352$fecha_dato)

x <- xts(as.numeric(x[,1]), index(x)) #xts / zoo objects are a matrix with an index attribute. 
chartSeries(x, TA=NULL)

macd = MACD(x, nFast=12, nSlow=26,nSig=9,maType=SMA,percent = FALSE)
chartSeries(x, TA='addMACD()')
signal = Lag(ifelse(macd$macd < macd$signal, -1, 1))
returns = ROC(x)*signal
returns = returns['2017-01-01/2017-06-01']
portfolio = exp(cumsum(returns))
plot(portfolio)
table.Drawdowns(returns, top=5)
table.DownsideRisk(returns)
charts.PerformanceSummary(returns)

```

## signal

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```


