---
title: "ETFsIFBacktestingStrategy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# TTR lets use a little of thecnical analisys finding the  overbought and oversold etf or investmend funds 


*italic*   **bold**

```{r  aa, echo=T , message=F, warning=F}

rm(list = ls())

df <-readRDS("../input/etfs_20171108.rds")

library(TTR) #  rsi() for calculating simple moving average

vector <- unique(df$isin)
dfa <- data.frame(stringsAsFactors=FALSE) 

for (i in vector)
{

  
  e <- dplyr::filter(df,  isin == i)
  {
      e <- e[order(as.Date(e$date, format="%Y-%m-%d")),]
      
      rsi <- RSI(e$Close, n=14)
      e$rsi <-rsi
      tail <- tail(e, 1)
      dfa <-rbind( dfa ,tail )
  }
  else {   print( paste0( "the product",vector,"is too small" )) } 
}


t <-tail (dfa[order(dfa$rsi),], 1)

h <-head (dfa[order(dfa$rsi),], 1)

```


# lets see the overboguht 

* Item 1
* Item 2
    + Item 2a
    + Item 2b
    

```{r  eda1, echo=T , message=F, warning=F}
library(plotly)


p1 <- plot_ly() %>% 
  add_trace(data=dplyr::filter(df,  isin == h$isin),
            x = ~date, y = ~Close, type="scatter", mode="lines", name = h$isin) 
p1


p1 <- plot_ly() %>% 
  add_trace(data=dplyr::filter(df,  isin == 'IE00B4PY7Y77'),
            x = ~date, y = ~Close, type="scatter", mode="lines", name = 'IE00B4PY7Y77') 
p1

``` 

# lets see the oversold 




```{r  eda2, echo=T , message=F, warning=F}
p2 <- plot_ly() %>% 
    add_trace(data=dplyr::filter(df,  isin == t$isin),
            x = ~date, y = ~Close, type="scatter", mode = "lines" , name = t$isin) 
p2

```





```{r scraping,include=FALSE} 

library(TTR) #  SMA() for calculating simple moving average


historical.data.overbought <- df %>%  filter(isin == t$isin)

ob <- historical.data.overbought[order(as.Date(historical.data.overbought$date, format="%Y-%m-%d")),]

ob$SMA26 <- SMA(ob$Close, 26)
ob$SMA12 <- SMA(ob$Close, 12)
ob$SMA200 <- SMA(ob$Close, 200)



GB00B1XFGM25[1:735,13] <-GB00B1XFGM25[26:760,10]
GB00B1XFGM25 [1:749,14] <-GB00B1XFGM25[12:760,11]
GB00B1XFGM25[1:561,15]<-GB00B1XFGM25[200:760,12]

GB00B1XFGM25[10:12] <-GB00B1XFGM25[13:15]

GB00B1XFGM25[13:15] <- NULL

p <-plot_ly() %>% 
  add_trace(data= ob,
            x = ~date, y = ~Close, type="scatter", mode="lines", name = "historical.data.overbought") %>% 
  add_trace(x = ~date,y = ~SMA26, type="scatter", mode="lines", name = "SMA26") %>% 
 add_trace(x = ~date,y = ~SMA12, type="scatter", mode="lines", name = "SMA12") %>% 
   add_trace(x = ~date,y = ~SMA200, type="scatter", mode="lines", name = "SMA200") 

p
print(p)
 
```


# what kind of etfs we have ?
# how many we have by 

```{r pressure, echo=FALSE}

aa <- dfa %>% group_by( category) %>%  filter(type == 'ETFEI' )  %>% summarise(count= n())

pp <- plot_ly(aa, x = ~category, y = ~count,  
              type = 'scatter' , mode = 'markers', marker = list(size = 15))  %>% 

layout(title = "numbers of etfs by category",  showlegend = TRUE)
pp


aa <- dfa %>% group_by( category) %>% filter(type == 'ITEI' )  %>%   summarise(count= n())

pp <- plot_ly(aa, x = ~category, y = ~count,  
              type = 'scatter' , mode = 'markers', marker = list(size = 15))  %>% 

layout(title = "numbers of IF by category",  showlegend = TRUE)
pp

```


# lets inferir some basica materials

```{r pressure, echo=FALSE}
thingslooklikeMaterial <- c("gold",'Physical', 'silver')


MFEIInc <- dfa  %>%  filter( grepl(paste(thingslooklikeMaterial, collapse="|"),LegalName , ignore.case=T )) 

```


#under review 

```{r pressure, echo=FALSE}
stock <- df  %>% filter(isin == 'IE00B4PY7Y77')

plot(stock$Close)

dygraph(stocks.ts$TWTR$Close, main = "TWTR Stock Price") %>%
  dyRangeSelector(dateWindow = c("2013-12-18", "2016-12-30"))

head(SMA(stocks.ts$TWTR$Close, 200))
head(SMA(stocks.ts$TWTR$Close, 50))

mov.avgs<-function(stock.df){
  stock.close<-stock.df[,4]
  ifelse((nrow(stock.df)<(2*260)),
         x<-data.frame(stock.df, 'NA', 'NA'),
         x<-data.frame(stock.df, SMA(stock.close, 200), SMA(stock.close, 50)))
  colnames(x)<-c(names(stock.df), 'sma_200','sma_50')
  x<-x[complete.cases(x$sma_200),]
  return(x)
}

stocks.ts<-pblapply(stocks.ts, mov.avgs)

dygraph(stocks.ts$FOX[,c('sma_200','sma_50')],main = 'FOX Moving Averages') %>%
  dySeries('sma_50', label = 'sma 50') %>%
  dySeries('sma_200', label = 'sma 200') %>%
  dyRangeSelector(height = 30) %>%
  dyShading(from = '2016-4-28', to = '2016-7-27', color = '#CCEBD6') %>%
  dyShading(from = '2016-7-28', to = '2016-12-30', color = '#FFE6E6')


```


