---
title: "funds strategy backtest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## funds strategy


```{r setup, echo=T, include=T, message=F, warning=F}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(jsonlite)  
library(XML)       
library(RCurl)     
library(stringr)   
library(plyr)      
library(dplyr)     
library(lubridate) 

```



```{r cars}


url_MFEI <-  "http://lt.morningstar.com/api/rest.svc/9vehuxllxs/security/screener?page=1&pageSize=3000&sortOrder=LegalName%20asc&outputType=json&version=1&languageId=en-GB&currencyId=GBP&universeIds=FOGBR%24%24ALL_3521&securityDataPoints=SecId%7CName%7CTenforeId%7CholdingTypeId%7Cisin%7Csedol%7CCustomAttributes1%7CCustomAttributes2%7CCustomExternalURL1%7CCustomExternalURL2%7CCustomExternalURL3%7CCustomIsClosed%7CCustomIsFavourite%7CCustomIsRecommended%7CQR_MonthDate%7CLegalName%7CCustomBuyFee%7CYield_M12%7COngoingCharge%7CCustomCategoryId3Name%7CStarRatingM255%7CQR_GBRReturnM12_5%7CQR_GBRReturnM12_4%7CQR_GBRReturnM12_3%7CQR_GBRReturnM12_2%7CQR_GBRReturnM12_1%7CCustomMinimumPurchaseAmount%7CCustomValue2%7CCustomAdditionalBuyFee%7CCustomSellFee%7CGBRReturnM0%7CGBRReturnM12%7CGBRReturnM36%7CGBRReturnM60%7CGBRReturnM120&filters=&term=&subUniverseId=MFEI"

MFEI <-getURL(url_MFEI) %>% fromJSON()  %>% as.data.frame

names(MFEI)

names(MFEI) <- gsub("rows.", "", names(MFEI))


MFEIInc <- MFEI  %>%  filter( !grepl("Acc",LegalName)  ) # we generate another dataset with just the incremental funds



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

Bonds <-filter( MFEIInc, CustomCategoryId3Name =="Bonds"  ) 


MFEIInc <- url_MFEI


temp <- MFEIInc %>% select(GBRReturnM0,GBRReturnM12,GBRReturnM36,isin,Name,CustomCategoryId3Name)

temp <- na.omit(temp) 

temp <- temp %>% group_by(CustomCategoryId3Name)%>% summarise(returnbycat=mean(GBRReturnM0))


plot_ly(temp, x = ~returnbycat, color = ~CustomCategoryId3Name, type = "box") %>%
  layout(title = "average score  for each type of rating",  showlegend = TRUE)

```
































































```{r pressure, echo=FALSE}
library(devtools)
install_github("ropensci/plotly")

 
p <- plot_ly(
  type = 'table',  # Specify type of plot as table
  
  # header is a list and every parameter shown below needs 
  # to be specified. Note that html tags can be used as well
  
  header = list(
    
    # First specify table headers
    # Note the enclosure within 'list'
    
    values = list(list('<b>EXPENSES</b>'),
                  list('<b>Q1</b>'),
                  list('<b>Q2</b>'), 
                  list('<b>Q3</b>'), 
                  list('<b>Q4</b>')),
    
    # Formatting 
    line = list(color = '#DFE8F3'),
    align = c('left','left','left','left','left'),
    font = list(color = c('#506784', '#506784', '#506784', '#506784', '#ab63fa'), size = 14)
  ),
  
  # Specify individual cells
  
  cells = list(
    
    # Now specify each cell content
    
    values = list(
      c('Salaries', 'Office', 'Merchandise', 'Legal', '<b>TOTAL</b>'),
      c(1200000, 20000, 80000, 2000, 12120000),
      c(1300000, 20000, 70000, 2000, 130902000),
      c(1300000, 20000, 120000, 2000, 131222000),
      c(1400000, 20000, 90000, 2000, 14102000)),
    
    # Formatting
    line = list(color = '#DFE8F3'),
    align = c('left', 'left', 'left', 'left', 'left'),
    font = list(color = c('#506784', '#506784', '#506784', '#506784', '#ab63fa'), size = 14),
    height = 48
    )) %>% 
  
  # Layout is needed to remove gridlines, axis zero lines and ticktext 
  # or else they will also show up
  
  layout(xaxis = list(zeroline = F, showgrid = F, showticklabels = F, domain = c(0, 0.5)),
         yaxis = list(zeroline = F, showgrid = F, showticklabels = F))
 
p
```